### ISSUE TITLE
No channels for Orange TV Reunion?

### ISSUE THREAD

**Issue by starmate** [BreizhReloaded/plugin.video.orange.fr#10]
Hi,

Thanks for this addon.

I am trying to make it work for Orange TV Réunion. 

When I am trying to fetch channels from IPTV Manager, I have the following error : orange TV error (check log for more details).

I've noticed that from resources/lib/providers/fr/orange.py, you define channels numbers. I believe that this would be difference for Reunion. Do you think I could update this? If yes, Do you know how I could retrive those information?

Thanks,

Jon

**Comment by starmate** [comment]
Oui, j'ai essayé plusieurs fois. J'ai fait un switch de Orange FR > Orange Réunion et inversement.

Je regarde tout ça lorsque j'ai un peu de temps et je reviens vers toi... ça ne doit pas être bien méchant :)

Merci encore.

**Comment by BreizhReloaded** [comment]
Alors @starmate, du nouveau depuis la Réunion ? Tiens-moi au courant, pour que je puisse faire les corrections nécessaires et publier une éventuelle nouvelle version !

**Comment by BreizhReloaded** [comment]
Je pense que j'ai fini par trouvé ! Une obscure histoire de `&` et de `?` dans les URL. Dans le doute, et parce que ça semble fonctionner un peu depuis chez moi, j'ai publié la nouvelle version.
