### ISSUE TITLE
full HD

### ISSUE THREAD

**Issue by nicomarti83** [BreizhReloaded/plugin.video.orange.fr#11]
salut,
est-ce normal que le flux soit uniquement en 720p et pas 1080p?
merci d'avance

**Comment by BreizhReloaded** [comment]
Salut @nicomarti83 !
Le flux récupéré est le flux renvoyé par défaut par Orange, je t'avoue que je ne me suis pas trop posé la question. Est-ce qu'il y a des flux en 1080p disponibles depuis la TV web ? Si oui, alors on devrait pouvoir les récupérer. Sinon, c'est que la limite vient d'Orange, un peu comme pour les sous-titres et la VO (disponibles depuis le boitier TV, mais pas depuis l'appli mobile ou le web).

**Comment by nicomarti83** [comment]
Je viens d'essayer et l'interface ne permet pas de changer la résolution et j'ai essayé d'avoir l'information mais impossible de trouver...

**Comment by BreizhReloaded** [comment]
Pareil, je viens de regarder, et je n'ai pas trouver de paramètres qui pourraient correspondre à ça. Je clôture la discussion, mais n'hésite pas à la réouvrir si tu vois un changement sur la TV web !
