### ISSUE TITLE
xbmc.python version 3.0.0

### ISSUE THREAD

**Issue by Manumie** [BreizhReloaded/plugin.video.orange.fr#12]
Bonjour,

Merci et bravo pour votre plugin que je n'ai malheureusement pas encore pu tester.

J'ai un Raspberry Pi sous Raspbian Buster et j'ai installé la version officielle de Kodi (Leia 18.7)
J'ai des bases en Python et en Debian, mais je découvre (avec bonheur) Kodi et le Raspberry Pi.
J'ai téléchargé le zip du plugin, mais lorsque je veux l'installer, j'ai un message d'erreur à propos de xbmc python version 3.0.0 non trouvé.
J'ai vu que tous les releases du plugin orange.fr dépendent de xbmc python 3.0.0
J'ai cru comprendre que la version 3.0.0 de xbmc.python est disponible à partir de Kodi 19, mais je n'ai pas trouvé de build pour Raspbian Buster (qui pourtant est livré avec Python 3.7.3)

Que me recommandez-vous ?
* me lancer dans un build manuel de Kodi 19.1 ? (je vais regarder les forums pour voir les pré-requis)
* essayer de modifier, dans le fichier `addon.xml` du plugin, le requirement de xbmc python pour la version livrée avec Kodi 18.7, mais je ne sais pas laquelle... J'ai trouvé un bout de script [ici](https://forum.kodi.tv/showthread.php?tid=328001&pid=2699454#pid2699454) mais il faut que ce soit dans un addon (vu qu'on ne peut pas importer xbmc en dehors de l'environnement Kodi), et j'en suis pas encore là ^^'
* contourner le problème en essayant d'intégrer une playlist m3u des chaînes fournies par Orange dans IPTVManager ?

Merci d'avance pour vos conseils !

**Comment by BreizhReloaded** [comment]
Salut Manumie,

Je n'ai jamais trouvé de fichier m3u à jour, c'est pour ça que j'ai fini par développer cet addon !

Pour répondre à ton problème, cet addon pourrait en effet facilement fonctionner avec Python 2. Il faudrait faire le tour rapidement des imports parce que certaines syntaxes changent entre les deux versions, et changer la dépendance dans `addon.xml`. Pour le numéro de version exacte, on pourrait simplement regarder ce qui est indiqué dans d'autres addons fonctionnant sous Kodi 18. Si tu clones le projet et que tu l'ouvres avec un éditeur configuré avec Python 2, ça ne devrait pas être trop compliqué. 

Pour la compilation manuelle de Kodi 19, là ça sort complètement de mon champ de compétences. Mais [cette version](https://kodi.tv/download/raspberry-pi) ne fonctionne pas du tout ?

**Comment by Manumie** [comment]
Merci pour ta réponse !
En effet, pour les m3u, je n'ai rien trouvé de probant non plus...
Le lien que tu indiques pour la v 19.1 nous vend du rêve ;-) : il n'y a pas encore de build officiel pour Kodi 19 sur Raspberry Pi OS... C'est juste une question de temps, bien sûr. 
Après, il existe des images de Kodi 19 qui tournent sur le RPi, mais je veux garder un vrai OS, plus Kodi.
Et la compil nécessite beaucoup de dépendances, il faut aussi complier les pvr... Bref, c'est du taf.
Du coup, la piste d'adapter ton plugin pour xbmc python v < 3.0 est sans doute la bonne... Je ne vais pas avoir le temps de m'y mettre tout de suite, mais je le note !

**Comment by BreizhReloaded** [comment]
Ok. N'hésite pas à me tenir au courant !

**Comment by flopp26** [comment]
Hello, je viens de voir que le topic est cloturé, mais je cherche aussi une version de ton super plugin pour kodi 18, je suis sur PC,  mais j'ai plein de soucis avec kodi 19.. la première release est aussi sur python 3?

**Comment by BreizhReloaded** [comment]
Hélas oui, j'ai débuté sur Kodi 19 directement. Rendre l'addon compatible Kodi 18 n'est pas compliqué en soi, mais c'est malheureusement du temps que je n'ai pas pour le moment. Je me suis lancé sur d'autres chantiers que j'aimerais clôturer avant. 

Au mieux dans quelques mois, quand je regarderai les pipelines de publication vers le dépôt de Kodi. J'aimerais à ce moment-là publier les deux versions en même temps.

**Comment by flopp26** [comment]
Merci de ta réponse.. on verra quand tu seras disponible ;-)

**Comment by wail-fajr-rd** [comment]
Bonjour à tous,
J'ai tenté de porter ce plugin video orange sur Python 2. J'ai finalement pu arriver au bout de l'installation du plugin sur mon Kodi 18 (LibreElec 9 sur Raspberry Pi 3).
Vous pouvez trouver ce code légèrement modifié dans ce fork sur la branche Kodi 18 https://github.com/wail-fajr-rd/plugin.video.orange.fr/tree/kodi18
La liste des changements que j'ai faits (en anglais) :
* change xbmc version from 3 to 2...
* remove type hinting in function signatures
* remove type hinting for class and instance attributes from classes
* add the enum34 package in lib for "from enum import Enum"
* remove dataclasses module import, which seemed to be unused
* adapt urllib imports

Je précise que je suis à peu près nouveau sur Python et totalement nouveau sur le développement Kodi.

 @BreizhReloaded tu peux évidemment te servir dans ce code, même si je ne garantis rien en terme de qualité comme annoncé ci-dessus.
Je précise que même si l'installation a finalement fonctionné, je n'ai pas encore pu regarder la TV Orange sur mon Kodi. Je ne vois pas de raison particulières à cela : portage incomplet qui provoquerait des erreurs silencieuses ou problème d'accès au flux TV Orange de ma part?

**Comment by flopp26** [comment]
Hello, merci @wail-fajr-rd  pour le portage, je viens de tester et erreur lors de la maj du guide et aucune chaine ne se lance. Tant pis ^^

**Comment by BreizhReloaded** [comment]
Top, bien joué  @wail-fajr-rd ! Désolé de ne pas être revenu vers toi plus tôt, mais en effet, le mieux reste de confronter l'addon directement dans Kodi, au moins on voit tout de suite où ça bloque. Si le problème est au niveau de InputStream Adaptive, tu peux essayer de changer la version demandée dans `addon.xml`.

**Comment by klems29** [comment]
Bonjour, merci pour cet addon. J'ai tenté une installation sur mi box tv 3 en kodi 18.9, même pb avec python. En 19.3, l'installation fonctionne, mais après je n'arrive pas à aller plus loin. J'ai bien fait l'installation des dépendances ... mais rien ne s'affiche au niveau TV :/

**Comment by BreizhReloaded** [comment]
@klems29

C'est normal pour la 18.9, cet addon n'est en l'état pas compatible. Pour tes soucis en 19.3, je t'invite à bien vérifier ta configuration, plusieurs personnes ont déjà eu le même problème parce qu'ils n'avaient pas exemple pas configuré IPTV Simple PVR avec IPTV Manager (tu peux jeter un œil dans les sujets clôturés). Si le problème persiste, ouvre une nouvelle issue pour bien séparer les problèmes.
