### ISSUE TITLE
Orange TV Réunion, problème de mise à jour des chaines

### ISSUE THREAD

**Issue by starmate** [BreizhReloaded/plugin.video.orange.fr#14]
Hello,

J'espère que tu vas bien... je me suis rendu compte que j'ai complètement oublié de répondre au dernier message que tu m'as envoyé et je m'en excuse.

Le problème venait certainement du fait que tu as mis ceci :
`endpoint_streams = 'https://mediation-tv.orange.fr/all/live/v3/applications/PC/channels&mco=ORE',`
et en réalité, il aurait fallut utiliser ceci :
`endpoint_streams = 'https://mediation-tv.orange.fr/all/live/v3/applications/PC/channels?mco=ORE',`

Juste le '&' à remplacer par '?'...

Je fais néanmoins face à un nouveau problème... je n'arrive plus à rafraichir les chaines depuis hier et voici le message d'erreur que j'ai :

`ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'square'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jonat\AppData\Roaming\Kodi\addons\plugin.video.orange.fr\resources\addon.py", line 58, in <module>
                                                       plugin.run()
                                                     File "C:\Users\jonat\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "C:\Users\jonat\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "C:\Users\jonat\AppData\Roaming\Kodi\addons\plugin.video.orange.fr\resources\addon.py", line 48, in iptv_channels
                                                       IPTVManager(port, get_provider()).send_channels()
                                                     File "C:\Users\jonat\AppData\Roaming\Kodi\addons\plugin.video.orange.fr\resources\lib\iptvmanager.py", line 25, in send
                                                       sock.sendall(json.dumps(func(self)).encode()) # pylint: disable=not-callable
                                                     File "C:\Users\jonat\AppData\Roaming\Kodi\addons\plugin.video.orange.fr\resources\lib\iptvmanager.py", line 34, in send_channels
                                                       return { 'version': 1, 'streams': self.provider.get_streams() }
                                                     File "C:\Users\jonat\AppData\Roaming\Kodi\addons\plugin.video.orange.fr\resources\lib\provider_templates\orange.py", line 81, in get_streams
                                                       'logo': channel['logos']['square'],
                                                   KeyError: 'square'
                                                   -->End of Python script error report<--`

Aurais-tu une idée de l'origine du problème? Est-ce que ça fonctionne toujours pour la Orange TV France?

Merci d'avance

**Comment by starmate** [comment]
Bonjour,

Je ne sais pas si ça va aider, mais j'ai trouvé la solution au problème. Le fichier xml (de chanel si je ne me trompe pas) à changé un peu.

Du coup, j'ai ajouté cette condition dans plugin.video.orange.fr/resources/lib/provider_templates/orange.py (ligne 77) :
`if "name" in channel and "logos" in channel and "square" in channel['logos']:`

Du coup on a :
`        for channel in channels:
            if "name" in channel and "logos" in channel and "square" in channel['logos']:
                streams.append({
                    'id': channel['id'],
                    'name': channel['name'],
                    'preset': channel['zappingNumber'],
                    'logo': channel['logos']['square'],
                    'stream': 'plugin://plugin.video.orange.fr/channel/{id}'.format(id=channel['id']),
                    'group': [group_name for group_name in self.groups if int(channel['id']) in self.groups[group_name]]
                })

        return streams`

Voila, j'espère que ça aidera... je suppose que vous aviez le même problème pour la métropole...

**Comment by sae-gfc** [comment]
Bonjour
Les informations des chaînes sont récupérées de : 
https://mediation-tv.orange.fr/all/live/v3/applications/PC/channels?mco=ORE
Le problème vient du fait qu'il n'y a pas de logo pour certaines chaînes  (ex: 13 pour TFX)

Le correctif donné par starmate n'ajoute la chaîne que si certaines clefs du dictionnaire sont présentes.
Dans le même fichier j'ai fait à la place ceci afin que la chaine soit ajoutée même sans logo présent (il y aura le logo OrangeTM à la place) :
```
       for channel in channels:
            if 'square' in channel['logos']:
                logo = channel['logos']['square']
            else:
                logo = ''
            streams.append({
                'id': channel['id'],
                'name': channel['name'],
                'preset': channel['zappingNumber'],
                #    'logo': channel['logos']['square'],
                'logo': logo,
```
Vincent

**Comment by BreizhReloaded** [comment]
Bien vu messieurs ! J'ai corrigé ça en utilisant un petit ternaire, ça tient sur la même ligne ;) C'est publié avec le numéro de version 1.3.1, tenez-moi au courant !

**Comment by BreizhReloaded** [comment]
Petit correctif : prenez la 1.4.0, il reste quelques bugs sur la 1.3.1.

**Comment by starmate** [comment]
Merci 👌👍
