### ISSUE TITLE
Chaines payantes

### ISSUE THREAD

**Issue by Arias800** [BreizhReloaded/plugin.video.orange.fr#15]
Bonjour,
Merci pour l'addon, c'est une excellente idée.
Je viens de voir que tu te demandais dans la description si ça fonctionne aussi pour les chaines payantes.
Je peux donc confirmer que oui.
Ça fonctionne parfaitement sans aucune action requise de la part de l'utilisateur.
![image](https://user-images.githubusercontent.com/24809312/144433668-df5ff897-3b22-439f-aca1-4768bff83671.png)

Ce n'est pas une information importante, mais vu que je peux le confirmer, autant le faire.

**Comment by BreizhReloaded** [comment]
Salut Arias;

Tu es le premier retour que j'ai sur ce point, je suis content de voir que ça fonctionne sans avoir besoin de rajouter un module supplémentaire.

Merci beaucoup pour l'info !
