### ISSUE TITLE
login

### ISSUE THREAD

**Issue by thobonho** [BreizhReloaded/plugin.video.orange.fr#16]
Ca à l'air super mais je ne sais pas où entrer mes identifiants... A moins que le flux vidéo ne soit disponible seulement depuis une connexion internet Orange/Sosh ?

**Comment by BreizhReloaded** [comment]
C'est exactement ça. Il doit peut-être y avoir un moyen de s’authentifier depuis un autre opérateur, mais c'est le même problème que d'étendre ça en dehors de Orange : ça me demande de bosser depuis une autre connexion.

Par curiosité, est-ce qu'il y a un captcha quand tu te connectes sur la TV web avec tes identifiants ?

**Comment by thobonho** [comment]
Dommage pour moi... :(
Et pour répondre à ta question, oui, j'ai souvent un captcha à résoudre
quand je me connecte chez Orange.

Vais essayer de creuser la question de mon côté mais dis moi si je peux
faire quelque chose aider

**Comment by BreizhReloaded** [comment]
Ok. Le problème du captcha, c'est que ça n'est pas automatisable, et donc un gros frein à une utilisation depuis un autre opérateur en utilisant des identifiants Orange/Sosh.

A défaut, pour les cas où Orange ne demande pas de captcha, il te suffit "simplement" de regarder ce qui se passe dans ton navigateur via la console de développement et de faire un peu de rétro-ingénierie sur ce que tu vois. Une fois que tu as isolé les appels pour l'authentification, on peut penser à une implémentation.
