### ISSUE TITLE
problème de mise à jour des chaines malgré version1.5.0

### ISSUE THREAD

**Issue by crocketear** [BreizhReloaded/plugin.video.orange.fr#18]
Bonjour, malgré l'installation de la 1.5 .0, à chaque fois que j'utilise d'autres addons sur Kodi et que je reviens sur la TV, les chaines disparaissent et on voit que ça bloque sur la MAJ de l'enregistreur video (qui reste à 0%).
Je dois donc soit rebooter kodi, soit passer par les paramètres du plugin pour faire manuellement la mise à jour de IPTVmanager.

**Comment by BreizhReloaded** [comment]
Et quand tu rafraîchis les chaînes manuellement depuis IPTV Manager, elles s'affichent bien ? Est-ce que tu as le fichier en cache des chaînes dans le dossier data de l'addon ?

**Comment by BreizhReloaded** [comment]
Et de quels autres addons parles-tu ?

**Comment by crocketear** [comment]
Bon, j ai désinstallé,  IPTV simple, IPTV manager, CatchUp&Tv et Orange, et tout réinstallé et ça semble mieux. On va voir à  l'usage.

**Comment by BreizhReloaded** [comment]
Ok, étrange, mais bonne nouvelle ! N'hésite pas à rouvrir la discussion si jamais.

**Comment by crocketear** [comment]
Je me permets de réouvrir ce post, car j'ai bien un souci qui perdure : c'est la mise à jour automatique de IPTV manager qui ne se fait pas, je suis obligé d'entrer dans les paramètres de l'addon (orange-> paramètres IPTV Manager -> refresh list ).
Et même ce refresh ne marche pas à tous les coups (aléatoire) et je dois redémarrer Libreelec pour que ça refonctionne.

**Comment by BreizhReloaded** [comment]
Arf, dommage. Dans ce cas, je pense que le mieux c'est d'ouvrir une issue directement chez eux : https://github.com/add-ons/service.iptv.manager

**Comment by crocketear** [comment]
Une autre solution à tester est de passer par PVR IPTV Simple, mais je ne trouve pas les fichiers .m3u8 et.xml évoqués dans le tuto d'installation de l'addon Orange. Ils sont où exactement ? 
Merci d'avance;

**Comment by BreizhReloaded** [comment]
Dans le dossier où Kodi stocke ses fichiers (AppData sous Windows) : `Kodi/userdata/addon_data/plugin.video.orange.fr`
