### ISSUE TITLE
Problème d'intégration sous Mi Box Tv

### ISSUE THREAD

**Issue by klems29** [BreizhReloaded/plugin.video.orange.fr#19]
Bonjour, merci pour cet addon. 

J'ai tenté une installation sur mi box tv 3 en kodi 18.9, même pb avec python. 

En 19.3, l'installation fonctionne, mais après je n'arrive pas à aller plus loin. J'ai bien fait l'installation des dépendances ... mais rien ne s'affiche au niveau TV :/

**Comment by BreizhReloaded** [comment]
Tu as bien configuré IPTV Simple PVR et IPTV Manager ? Va voir ici #17

**Comment by klems29** [comment]
Du côté de IPTV Manager j'ai bien validé en auto. 
Du côté de IPTV Simple PVR, j'ai un m3u non fonctionnel (avant de tester ton addon). Ton addon semble l'avoir écrasé pour un m3u en local

**Comment by klems29** [comment]
Et je suis bien connecté sur ma livebox Sosh

**Comment by klems29** [comment]
proof.pepper.com/f/wSRQUp2hGj.jpeg
proof.pepper.com/f/N3xmWZKxdf.jpeg
proof.pepper.com/f/OQgg7czkIJ.jpeg
proof.pepper.com/f/XCV8lRqLOf.jpeg
proof.pepper.com/f/EABfSp6QnH.jpeg

**Comment by BreizhReloaded** [comment]
Ok. Oui, c'est IPTV Manager qui s'occupe de générer un nouveau .m3u. Est-ce que tu as forcé le chargement des chaînes depuis IPTV Manager ? Tu peux aussi effacer les données TV depuis les réglages de Kodi, pour forcer la prise en compte du nouveau fichier.

**Comment by klems29** [comment]
En effacent les données TV, et en retournant sur IPTV manager, ça m'a bien chargé les chaines via ton addon 
Par contre impossible de lire les chaînes, j'ai un message d'erreur : 
proof.pepper.com/f/2eP7WdbGN0.jpeg

**Comment by BreizhReloaded** [comment]
Salut Klems, est-ce que tu peux plutôt m'envoyer les logs de Kodi ? Je ne peux hélas pas grand chose avec uniquement le popup d'erreur.

**Comment by klems29** [comment]
Salut. Où est-ce que je peux te les envoyer ?

**Comment by BreizhReloaded** [comment]
Tu peux directement les ajouter en pièce-jointe à tes messages ici :)

**Comment by klems29** [comment]
Salut.
Le lien des logs : https://paste.kodi.tv/labeluroso

**Comment by klems29** [comment]
Bonjour. 

Je reviens vers toi pour savoir si une solution à mon problème a été trouvé ? 

Te remerciant par avance

**Comment by BreizhReloaded** [comment]
Salut klems29,

Non désolé, je n'ai vraiment pas eu de temps en janvier pour regarder ça en détail, désolé. Je devrais avoir plus de temps vers fin février.

**Comment by BreizhReloaded** [comment]
(mais l'erreur a l'air assez simple, ça ne devrait pas être trop compliqué à résoudre)
