### ISSUE TITLE
Test if we can use Orange FR also in Belgium

### ISSUE THREAD

**Issue by dagwieers** [BreizhReloaded/plugin.video.orange.fr#2]
There has been quite some interest to watch Orange TV on Kodi on our forums. I have found some candidates that may be able to help test and troubleshoot this add-on for Belgium.

If they take up the challenge, I will invite them to the Add-ons Slack channel to discuss. We can track the status in this ticket.

**Comment by dagwieers** [comment]
In case your are technical, we could track the API calls from the official app from: https://play.google.com/store/apps/details?id=com.orange.be.orangetv

**Comment by BreizhReloaded** [comment]
Perfect, thank you Dag! I personally can't access to those endpoints and the response data as I'm located in France, that's why I need some help here.

**Comment by skank01** [comment]
How can i help if its not too technical

**Comment by BreizhReloaded** [comment]
@skank01 thanks for trying!
Is your comment related to Orange Belgium, or are you located in France? If then, please open a dedicated issue so when can try to solve it. There may be an error due to the routing addon, but fortunately it can be downloaded manually.

**Comment by BreizhReloaded** [comment]
After some investigations, Orange Belgium API seems to be too different to consider merging the calls within the same addon. I'm closing this current issue.
