### ISSUE TITLE
Problèmes d'installation

### ISSUE THREAD

**Issue by Jucgshu** [BreizhReloaded/plugin.video.orange.fr#21]
Hello,

J'ai suivi le process d'insllation (https://github.com/BreizhReloaded/plugin.video.orange.fr/wiki/FR.-Installation-et-mise-en-place) sans grand succès.

J'ai donc installé le plugin Orange + le script module routing + IPTV Manager, mais aucune chaine n'apparait dans la section TV de Kodi (19.3).

Qu'ai-je manqué ?

Note : je suis sur CoreELEC.

Merci.

**Comment by Jucgshu** [comment]
Fixé en forçant l'intégration dans les paramètres du plugin.

**Comment by BreizhReloaded** [comment]
Top. Je vais faire des explications plus détaillées, vous êtes plusieurs à vous être faits avoir à cette étape :D

**Comment by vherrlein** [comment]
Comment fait on pour forcer les paramètres du plugin ?
