### ISSUE TITLE
Erreur lors du rafraîchissement des channels

### ISSUE THREAD

**Issue by frantz45** [BreizhReloaded/plugin.video.orange.fr#23]
Lorsque que je clic sur "Refresh channels and guide now" j'obtiens une erreur avant la fin.
Je pense que l'exception Python est liée : https://paste.kodi.tv/anokamejew
Mais sinon ça fonctionne bien j'ai bien accès aux chaînes :)

**Comment by BreizhReloaded** [comment]
Salut !
En effet, il semblerait que le contenu des appels pour avoir le programme soit vide. C'est noté, je vais essayer de reproduire ça.

**Comment by BreizhReloaded** [comment]
Salut @frantz45 !
Désolé de ne revenir vers toi que maintenant. Est-ce que tu arrives à charger ce json ? https://mediation-tv.orange.fr/all/live/v3/applications/PC/programs?period=today&mco=OFR
