### ISSUE TITLE
Addon ne fontionne plus du tout

### ISSUE THREAD

**Issue by Bestdoud** [BreizhReloaded/plugin.video.orange.fr#30]
Bonjour,
L'addon ne semble plus fonctionner du tout, Est-ce que d'autres personnes ont le même problème ?
merci de votre aide

Finalement le problème ne vient pas de l'addon

**Comment by fbelliard** [comment]
Hello,

J'ai le même problème.
Quelle était la source de ton problème ?

**Comment by Bestdoud** [comment]
C'est sûrement suite au passage à Kodi 20
C'était au niveau de l'addon IPTV simple client
Kodiba créé un fichier de config migrations et iptv manager n'arrivait plus à configurer IPTV simple client
Il a fallut que je recrée un fichier de config dans IPTV simple client sans mettre de nom. Du coup il s'est appelé inconnu
Dans IPTV manager j'ai reparametré IPTV manager et mis à jour les chaînes et guide
Ça a remarché sur tous mes appareils
J'espère avoir pu t'aider

**Comment by Rob-Lop** [comment]
Hello,
idem ici, ça ne fonctionne plus du tout sur Android TV… la mise à jour des chaines n'abouti à rien, plus aucune chaine n'apparait…
