### ISSUE TITLE
no channel in Kodi

### ISSUE THREAD

**Issue by Florent4223** [BreizhReloaded/plugin.video.orange.fr#6]
Hi
Thank you for the addon. I am trying to install it instead of going thru my Box from Orange.
I have a raspberry and I installed the librelec beta version of Kodi.
I then installed IPTV manager without any issues.

However, when I choose TV in Kodi, no channels are displayed.

Is there something I need to check/set up ?

Thanks

**Comment by BreizhReloaded** [comment]
Hello Flo,
Have you activated the IPTV Manager integration into the addon settings? Once done, you can open the IPTV Manager settings and refresh channels and guide. Then, you can force Kodi the reload the new data from TV > General > Erase data (same for the TV guide).

**Comment by Florent4223** [comment]
Hello
Yes, I confirm that I have gone to the IPTV manager extension> Configuration
That I started the automatic configuration then refreshed the channels

Unfortunately no channels appear in kodi> TV

I also like you asked to erase Kodu data, but nothing helps

**Comment by BreizhReloaded** [comment]
Go to the Orange TV settings, not the IPTV Manager settings ;)

**Comment by Florent4223** [comment]
Indeed it was only that, as much for me I thought I had already done it
I can see the channel list. On the other hand more out of curiosity: kodi downloads the DRM as expected. On the other hand, even if the installation seems to go well, when he wants to launch a protected channel, a message tells me that the files cannot be read. Did you have this problem?

**Comment by BreizhReloaded** [comment]
I'm glad to read you manage to get the channels.
First, are you able to watch a free channel like TF1 or France 2? About paid channels, as said in the readme file, I don't have any, so this part has not been tested.

**Comment by Florent4223** [comment]
thank you for your work :)
I only did tests with free channels ...(TF1, M6...channel TNT only)
I don't have subscriptions for pay channels

I think that it is more the recovery of the DRM which poses problem and their reading

thanks

**Comment by BreizhReloaded** [comment]
Let's keep things clean. Can you open an other issue about this new problem? Are you also able to share some logs? The DRM topic is handled by an other addon, InputStream Helper, but we'll see what's going on :)

**Comment by Florent4223** [comment]
ok 
I open a other issue
thanks
