### ISSUE TITLE
record channel?

### ISSUE THREAD

**Issue by Florent4223** [BreizhReloaded/plugin.video.orange.fr#8]
A simple question: but can we record the show?
either simply live or based on EPG? The recording could be either locally on the flash card or on the local network

thanks

**Comment by BreizhReloaded** [comment]
Hello Florent,

I know about this project called [IPTV Recorder](https://github.com/primaeval/plugin.video.iptv.recorder), but it's not up to date. Never tried it on Matrix though. If you hear about a solution, more linked to IPTV Simple globally than this Orange addon, I would love it!

**Comment by Florent4223** [comment]
thanks
