### ISSUE TITLE
guide tv vide

### ISSUE THREAD

**Issue by nicomarti83** [BreizhReloaded/plugin.video.orange.fr#9]
Bonjour,
tout d’abord merci pour ce pluggin. Après installation les chaines fonctionnent mais pas le guide TV reste désespérément vide...  Il n'y a pas beaucoup de doc concernant IPTV Manager donc j'ai peut être loupé quelque chose.
merci d'avance pour votre aide

**Comment by BreizhReloaded** [comment]
Salut @nicomarti83 !
Quelques pistes pour régler ton souci :
- est-ce que tu as bien configurer IPTV Simple ? il y a un bouton de configuration automatique depuis IPTV Manager
- est-ce que tu as essayer de forcer le rechargement de toutes les données ? Depuis IPTV Manager, puis suppression des données depuis les réglages TV de Kodi

**Comment by nicomarti83** [comment]
Ça fonctionne merci beaucoup 🙏
